### ISSUE TITLE
12월 29일 

### ISSUE THREAD

**Issue by parkchaelin** [parkchaelin/Project1#1]
1. work time 내부 db 저장 - mongoDB
   휴게시간 한번 입력해서 확인하면 총 work time db에 저장해서 다시 누르면 휴게 입력 안해도 되게 하기
   새로 추가되는 시간이 listview에서 위로 쌓이게 하기
   휴게시간 입력하고 커서 깜박임 고치기
   화면 나가도 시간 측정 안죽게 하기

2. Tel 연락처 추가 및 삭제?

3. image 이미지 크게 볼 때 옆으로 넘기기 가능하게

4. 디자인 수정

5. 클린 코드

**Comment by ki99** [comment]
휴게시간 한번 입력해서 확인하면 총 work time db에 저장해서 다시 누르면 휴게 입력 안해도 되게 하기
-> 버튼 누를때마다 database(sample.db)에 시간 추가되게 구현. myTimeList에 추가, 삭제하는 기능은 내일 구현할 예정

새로 추가되는 시간이 listview에서 위로 쌓이게 하기 -> 완료
